### ISSUE TITLE
Support other placeholder image services

### ISSUE THREAD

**Issue by eskimoblood** [ryhan/fixie#27]
Would be cool to support other placeholder services other then placeholder.it. [This site](http://net.tutsplus.com/articles/web-roundups/the-top-8-placeholders-for-web-designers/) list some of them. 
### Solutions:
- Implement all of this services
- Inject a function that returns the image url like this:
  
  fixie.setImagesService(
      function(width, height){ return "http://placekitten.com/" + width + "/" + height}  
  )
- Set a template where width and height will be replace by the image dimension
  fixie.setImagesService( "http://placekitten.com/__width **/** height__")

**Comment by eskimoblood** [comment]
made a pull request for with the third solution: https://github.com/rthprog/fixie/pull/28

**Comment by ryhan** [comment]
https://github.com/rthprog/fixie/tree/eskimoblood-master

Do you think it would make more sense to create functions like `fixie.setImagesService()`, `fixie.selector`, and what not, instead of throwing everything into .init()? I'm not sure if it's appropriate to change the .init formatting on people.

**Comment by eskimoblood** [comment]
Sure, will change my pull request.
